### ISSUE TITLE
ZeroBrane Studio completion

### ISSUE THREAD

**Issue by xenodium** [asmagill/hammerspoon-config-take2#1]
Noob to Hammerspoon, lua and ecosystem. I see you have some ZeroBrane debugging config (zerobrane.lua). Curious, do you also have hs code completion working within ZeroBrane?  I'm guessing you had to set path.lua, or the opposite (Hammerspoon to use ZeroBrane's interpreter)?

**Comment by asmagill** [comment]
Sorry I never responded; my experience using and integrating ZeroBrane with Hammerspoon is limited to Hammerspoon/hammerspoon#1268.

You can see the path changes we made there and hopefully that may help if you're still having an issue.
