### ISSUE TITLE
lua-vips and ZeroBrane

### ISSUE THREAD

**Issue by JaiGe** [asmagill/hammerspoon-config-take2#2]
Has anyone used the lua-vips library with ZeroBrane, or does anyone know how to set it up to work with ZeroBrane? I don't know anything about linking in ZeroBrane.
I have the lua-vips installed via luaRocks, and I just copied the vips file and folder to my project. I run this code:
`_vips = require "vips"`

...but I am getting an error:

> ...ZeroBraneStudioEduPack-1.70-win32\bin\lua.exe: .\vips.lua:5: cannot load module 'libvips-42.dll': The specified module could not be found.
> 
> stack traceback:
> 	[C]: in function 'load'
> 	.\vips.lua:5: in main chunk
> 	[C]: in function 'require'
> 	...jects-Workshop\Gideros_Projects\GettingFamiliar\test.lua:5: in main chunk
> 	[C]: at 0x00401b00
> Program completed in 1.14 seconds (pid: 1796).

The libvips-42.dll file is actually in a folder (vips-dev-8.6) containing include and lib files, but I don't know how to link them for ZeroBrane to find. I entered the path in the environment variables path, but that doesn't help.
Any ideas on how to do this?

**Comment by asmagill** [comment]
Sorry I never responded; my experience using and integrating ZeroBrane with Hammerspoon is limited to https://github.com/Hammerspoon/hammerspoon/issues/1268.

Hammerspoon is a macOS application -- by the looks of the error you've posted, it looks like you're using a Windows machine... while I can't say for certain, it looks like you may need to update your `package.cpath` variable to include the location of the `vips` library before trying to require it.

Hope you found your solution or that this may point you in the right direction if you're still looking.
